# Generated by Django 5.1.4 on 2024-12-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_communities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
